import HeroSection from "../about/components/HeroSection";
import { ExampleSection } from "./components/ExampleSection";
import { CTASection } from "./components/CTASection";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Portfolio Examples | AI Portfolio Generator",
  description:
    "Explore professionally designed AI-generated portfolio examples, customizable for developers, designers, marketers, and more.",
  keywords: [
    "portfolio examples",
    "AI portfolios",
    "web developer portfolio example",
    "designer portfolio example",
    "resume to portfolio AI",
  ],
  openGraph: {
    title: "Portfolio Examples",
    description: "See real portfolios generated by AI.",
    url: "https://yourdomain.com/examples",
    siteName: "AI Portfolio Generator",
    images: [
      {
        url: "/og-examples.png",
        width: 1200,
        height: 630,
      },
    ],
    locale: "en_US",
    type: "website",
  },
};

export default function ExamplesPage() {
  return (
    <main className="min-h-screen pt-15">
      <div className="max-w-7xl mx-auto px-6 py-12">
        {/* Header */}
        <HeroSection />

        {/* Examples Grid */}
        <ExampleSection />

        {/* CTA Section */}
        <CTASection />
      </div>
    </main>
  );
}
