export const runtime = "nodejs";
import { NextResponse } from "next/server";
import { Resend } from "resend";
import { adminSupabase } from "@/utils/supabase/admin";
import { enforceRateLimit } from "@/lib/rate-limit/enable-rate-limit";
import { acquireLock, releaseLock } from "@/lib/rate-limit/redis-lock";
import { cheapRateLimit } from "@/lib/rate-limit/ratelimit";

// Create new Resend client
const resend = new Resend(process.env.RESEND_API_KEY);

// Generate a 6-digit verification code to send via email
const generateCode = (): string => {
    return Math.floor(100000 + Math.random() * 900000).toString();
};

/**
 * POST /api/sendPreviewVerification
 *
 * This route:
 *  1. Accepts user's email + preview URL from the frontend
 *  2. Generates a 6-digit code
 *  3. Stores (email, code, preview_url) in Supabase
 *  4. Sends an email containing the code via Resend
 *
 * It does NOT send the preview link yet
 * @param req Request containing { email: string, previewUrl: string }
 * @returns NextResponse with success or error message
 */
export async function POST(req: Request) {
    // Parase JSON body
    const body = await req.json();
    const { email, fileContent, fileName } = body;

    // Validate fields
    if (!email || !fileContent || !fileName) {
        return NextResponse.json({ error: "Missing fields" }, { status: 400 });
    }

    // --- Enforce rate limits
    const rateLimitKey: string = `preview_verification:${email}`;
    const rateLimitResponse: NextResponse | null = await enforceRateLimit(
        cheapRateLimit,
        rateLimitKey,
    );

    if (rateLimitResponse) return rateLimitResponse;

    // --- Acquire lock for preventing concurrency
    const lockKey: string = `preview_verification:lock:${email}`;
    const lockAcquired = await acquireLock(lockKey, 600); // 10 minutes

    if (!lockAcquired)
        return NextResponse.json(
            {
                error: "Already sending email, must wait",
            },
            { status: 409 },
        );

    const code = generateCode();

    /**
     * Insert a row into the "email_verifications" table:
     *
     * email: user's email
     * code: the 6-digit verification code
     * preview_file_content: the html/css content
     * preview_file_name: the file name
     * created_at: automatically generated by Supabase
     *
     * This row will be used later to verify the code the user enters.
     */
    const { error: insertError } = await adminSupabase
        .from("email_verifications")
        .insert({
            email,
            code,
            preview_file_content: fileContent,
            preview_file_name: fileName,
        });

    // Handle insertion error
    if (insertError) {
        return NextResponse.json({ error: "DB Error" }, { status: 500 });
    }

    // Send email
    await resend.emails.send({
        from: "WebGen AI <noreply@portfoliogenai.com>",
        to: email,
        subject: "Your WebGen Verification Code",
        html: `
      <div style="font-family: Arial; padding: 20px">
        <h2>Your WebGen Verification Code</h2>
        <p>Enter this 6-digit code to verify your email:</p>
        <h1 style="letter-spacing: 4px;">${code}</h1>
        <p>This code expires in 10 minutes.</p>
      </div>
    `,
    });

    // --- Release lock
    await releaseLock(lockKey);

    return NextResponse.json({ success: true });
}
