import type {
  ConnectionData,
  EvidenceItem,
  HistoryEntry,
  SkillVerification,
  VerificationOverviewData,
} from "./verification.types"

export const MOCK_OVERVIEW: VerificationOverviewData = {
  overallScore: 73,
  tier: "Intermediate",
  totalSkills: 12,
  verifiedCount: 8,
  needsActionCount: 3,
  conflictCount: 1,
  lastRunDate: "2026-04-06T14:30:00Z",
  trustNote:
    "Scores are evidence-based and may change as new data is connected.",
}

export const MOCK_CONNECTIONS: ConnectionData[] = [
  {
    provider: "linkedin",
    displayName: "LinkedIn",
    status: "connected",
    connectedAt: "2026-03-15T10:00:00Z",
    profileUrl: "https://linkedin.com/in/johndoe",
    endorsementCount: 24,
    potentialPoints: 15,
    permissionScope: "Read-only profile & endorsements",
  },
  {
    provider: "github",
    displayName: "GitHub",
    status: "connected",
    connectedAt: "2026-03-10T08:00:00Z",
    profileUrl: "https://github.com/johndoe",
    endorsementCount: 0,
    potentialPoints: 20,
    permissionScope: "Read-only repos & contributions",
  },
  {
    provider: "website",
    displayName: "Website / Domain",
    status: "disconnected",
    connectedAt: null,
    profileUrl: null,
    endorsementCount: 0,
    potentialPoints: 10,
    permissionScope: "Domain ownership verification",
  },
  {
    provider: "other",
    displayName: "Other Portfolio Links",
    status: "pending",
    connectedAt: null,
    profileUrl: null,
    endorsementCount: 0,
    potentialPoints: 8,
    permissionScope: "Read-only public content",
  },
]

export const MOCK_SKILLS: SkillVerification[] = [
  {
    id: "skill-1",
    name: "React",
    score: 92,
    tier: "Expert",
    status: "verified",
    freshness: "fresh",
    lastVerified: "2026-04-05T12:00:00Z",
    evidenceCount: 14,
    endorsementCount: 5,
    certificationCount: 1,
    projectCount: 6,
    assessmentCount: 1,
    selfReportedCount: 1,
    conflictDetails: null,
  },
  {
    id: "skill-2",
    name: "TypeScript",
    score: 88,
    tier: "Advanced",
    status: "verified",
    freshness: "fresh",
    lastVerified: "2026-04-05T12:00:00Z",
    evidenceCount: 11,
    endorsementCount: 4,
    certificationCount: 1,
    projectCount: 4,
    assessmentCount: 1,
    selfReportedCount: 1,
    conflictDetails: null,
  },
  {
    id: "skill-3",
    name: "Node.js",
    score: 75,
    tier: "Advanced",
    status: "verified",
    freshness: "fresh",
    lastVerified: "2026-04-04T12:00:00Z",
    evidenceCount: 9,
    endorsementCount: 3,
    certificationCount: 0,
    projectCount: 4,
    assessmentCount: 1,
    selfReportedCount: 1,
    conflictDetails: null,
  },
  {
    id: "skill-4",
    name: "Next.js",
    score: 71,
    tier: "Advanced",
    status: "verified",
    freshness: "aging",
    lastVerified: "2026-03-20T12:00:00Z",
    evidenceCount: 7,
    endorsementCount: 2,
    certificationCount: 0,
    projectCount: 3,
    assessmentCount: 1,
    selfReportedCount: 1,
    conflictDetails: null,
  },
  {
    id: "skill-5",
    name: "CSS / Tailwind",
    score: 68,
    tier: "Advanced",
    status: "verified",
    freshness: "fresh",
    lastVerified: "2026-04-03T12:00:00Z",
    evidenceCount: 8,
    endorsementCount: 3,
    certificationCount: 0,
    projectCount: 3,
    assessmentCount: 1,
    selfReportedCount: 1,
    conflictDetails: null,
  },
  {
    id: "skill-6",
    name: "PostgreSQL",
    score: 60,
    tier: "Intermediate",
    status: "verified",
    freshness: "aging",
    lastVerified: "2026-03-15T12:00:00Z",
    evidenceCount: 5,
    endorsementCount: 1,
    certificationCount: 0,
    projectCount: 2,
    assessmentCount: 1,
    selfReportedCount: 1,
    conflictDetails: null,
  },
  {
    id: "skill-7",
    name: "Python",
    score: 45,
    tier: "Intermediate",
    status: "conflict",
    freshness: "aging",
    lastVerified: "2026-03-10T12:00:00Z",
    evidenceCount: 4,
    endorsementCount: 1,
    certificationCount: 0,
    projectCount: 1,
    assessmentCount: 1,
    selfReportedCount: 1,
    conflictDetails: [
      {
        source: "Resume",
        claim: "3 years professional Python experience",
        counterSource: "GitHub",
        counterClaim: "Only 4 Python repositories, last activity 18 months ago",
      },
    ],
  },
  {
    id: "skill-8",
    name: "GraphQL",
    score: 42,
    tier: "Intermediate",
    status: "verified",
    freshness: "stale",
    lastVerified: "2026-01-20T12:00:00Z",
    evidenceCount: 3,
    endorsementCount: 1,
    certificationCount: 0,
    projectCount: 1,
    assessmentCount: 0,
    selfReportedCount: 1,
    conflictDetails: null,
  },
  {
    id: "skill-9",
    name: "AWS",
    score: 38,
    tier: "Basic",
    status: "needs_action",
    freshness: "stale",
    lastVerified: "2026-01-05T12:00:00Z",
    evidenceCount: 3,
    endorsementCount: 0,
    certificationCount: 1,
    projectCount: 0,
    assessmentCount: 1,
    selfReportedCount: 1,
    conflictDetails: null,
  },
  {
    id: "skill-10",
    name: "Figma",
    score: 30,
    tier: "Basic",
    status: "needs_action",
    freshness: "aging",
    lastVerified: "2026-02-28T12:00:00Z",
    evidenceCount: 2,
    endorsementCount: 0,
    certificationCount: 0,
    projectCount: 1,
    assessmentCount: 0,
    selfReportedCount: 1,
    conflictDetails: null,
  },
  {
    id: "skill-11",
    name: "CI/CD",
    score: 22,
    tier: "Basic",
    status: "needs_action",
    freshness: "stale",
    lastVerified: "2025-12-15T12:00:00Z",
    evidenceCount: 2,
    endorsementCount: 0,
    certificationCount: 0,
    projectCount: 1,
    assessmentCount: 0,
    selfReportedCount: 1,
    conflictDetails: null,
  },
  {
    id: "skill-12",
    name: "Docker",
    score: 15,
    tier: "Unverified",
    status: "pending",
    freshness: "stale",
    lastVerified: "2025-11-01T12:00:00Z",
    evidenceCount: 1,
    endorsementCount: 0,
    certificationCount: 0,
    projectCount: 0,
    assessmentCount: 0,
    selfReportedCount: 1,
    conflictDetails: null,
  },
]

export const MOCK_EVIDENCE: EvidenceItem[] = [
  {
    id: "ev-1",
    skillId: "skill-1",
    skillName: "React",
    type: "project",
    source: "GitHub",
    description: "E-commerce dashboard with React 18 + hooks",
    date: "2026-03-28T12:00:00Z",
    quality: "high",
    url: "https://github.com/johndoe/ecommerce-dash",
  },
  {
    id: "ev-2",
    skillId: "skill-1",
    skillName: "React",
    type: "certification",
    source: "Meta",
    description: "Meta Front-End Developer Professional Certificate",
    date: "2026-02-15T12:00:00Z",
    quality: "high",
    url: null,
  },
  {
    id: "ev-3",
    skillId: "skill-1",
    skillName: "React",
    type: "endorsement",
    source: "LinkedIn",
    description: "Endorsed by 5 connections for React.js",
    date: "2026-04-01T12:00:00Z",
    quality: "medium",
    url: null,
  },
  {
    id: "ev-4",
    skillId: "skill-2",
    skillName: "TypeScript",
    type: "project",
    source: "GitHub",
    description: "Open-source CLI tool written in TypeScript",
    date: "2026-03-20T12:00:00Z",
    quality: "high",
    url: "https://github.com/johndoe/ts-cli",
  },
  {
    id: "ev-5",
    skillId: "skill-2",
    skillName: "TypeScript",
    type: "endorsement",
    source: "LinkedIn",
    description: "Endorsed by 4 connections for TypeScript",
    date: "2026-03-15T12:00:00Z",
    quality: "medium",
    url: null,
  },
  {
    id: "ev-6",
    skillId: "skill-3",
    skillName: "Node.js",
    type: "project",
    source: "GitHub",
    description: "REST API backend with Express + Node.js",
    date: "2026-03-10T12:00:00Z",
    quality: "high",
    url: "https://github.com/johndoe/api-backend",
  },
  {
    id: "ev-7",
    skillId: "skill-3",
    skillName: "Node.js",
    type: "assessment",
    source: "Platform",
    description: "Node.js proficiency assessment - Score: 87/100",
    date: "2026-02-20T12:00:00Z",
    quality: "high",
    url: null,
  },
  {
    id: "ev-8",
    skillId: "skill-4",
    skillName: "Next.js",
    type: "project",
    source: "Portfolio",
    description: "Full-stack Next.js portfolio site with SSR",
    date: "2026-01-15T12:00:00Z",
    quality: "medium",
    url: null,
  },
  {
    id: "ev-9",
    skillId: "skill-5",
    skillName: "CSS / Tailwind",
    type: "project",
    source: "GitHub",
    description: "Design system with Tailwind CSS components",
    date: "2026-03-25T12:00:00Z",
    quality: "high",
    url: "https://github.com/johndoe/design-system",
  },
  {
    id: "ev-10",
    skillId: "skill-6",
    skillName: "PostgreSQL",
    type: "project",
    source: "GitHub",
    description: "Database schema design for SaaS application",
    date: "2026-02-10T12:00:00Z",
    quality: "medium",
    url: null,
  },
  {
    id: "ev-11",
    skillId: "skill-7",
    skillName: "Python",
    type: "self_reported",
    source: "Resume",
    description: "3 years professional Python experience",
    date: "2026-01-01T12:00:00Z",
    quality: "conflicting",
    url: null,
  },
  {
    id: "ev-12",
    skillId: "skill-7",
    skillName: "Python",
    type: "project",
    source: "GitHub",
    description: "4 Python repositories with limited recent activity",
    date: "2024-10-15T12:00:00Z",
    quality: "low",
    url: "https://github.com/johndoe?tab=repositories&language=python",
  },
  {
    id: "ev-13",
    skillId: "skill-9",
    skillName: "AWS",
    type: "certification",
    source: "AWS",
    description: "AWS Cloud Practitioner (expired 2025)",
    date: "2024-06-01T12:00:00Z",
    quality: "low",
    url: null,
  },
  {
    id: "ev-14",
    skillId: "skill-9",
    skillName: "AWS",
    type: "self_reported",
    source: "Resume",
    description: "AWS experience with EC2, S3, Lambda",
    date: "2026-01-01T12:00:00Z",
    quality: "medium",
    url: null,
  },
  {
    id: "ev-15",
    skillId: "skill-10",
    skillName: "Figma",
    type: "project",
    source: "Portfolio",
    description: "UI/UX redesign case study for fintech app",
    date: "2026-02-20T12:00:00Z",
    quality: "medium",
    url: null,
  },
  {
    id: "ev-16",
    skillId: "skill-1",
    skillName: "React",
    type: "project",
    source: "Portfolio",
    description: "Real-time chat application with React + WebSockets",
    date: "2026-01-20T12:00:00Z",
    quality: "high",
    url: null,
  },
  {
    id: "ev-17",
    skillId: "skill-2",
    skillName: "TypeScript",
    type: "certification",
    source: "Platform",
    description: "TypeScript Advanced Concepts certification",
    date: "2026-03-01T12:00:00Z",
    quality: "high",
    url: null,
  },
  {
    id: "ev-18",
    skillId: "skill-11",
    skillName: "CI/CD",
    type: "project",
    source: "GitHub",
    description: "GitHub Actions workflow for automated testing",
    date: "2025-11-10T12:00:00Z",
    quality: "medium",
    url: null,
  },
  {
    id: "ev-19",
    skillId: "skill-12",
    skillName: "Docker",
    type: "self_reported",
    source: "Resume",
    description: "Docker containerization experience",
    date: "2026-01-01T12:00:00Z",
    quality: "low",
    url: null,
  },
  {
    id: "ev-20",
    skillId: "skill-8",
    skillName: "GraphQL",
    type: "project",
    source: "GitHub",
    description: "GraphQL API with Apollo Server",
    date: "2025-09-15T12:00:00Z",
    quality: "medium",
    url: "https://github.com/johndoe/graphql-api",
  },
]

export const MOCK_HISTORY: HistoryEntry[] = [
  {
    id: "hist-1",
    date: "2026-04-06T14:30:00Z",
    type: "full_run",
    summary: "Full verification scan completed. 2 skills upgraded, Python flagged with conflict.",
    scoreChange: 5,
    skillsAffected: 4,
  },
  {
    id: "hist-2",
    date: "2026-03-20T10:00:00Z",
    type: "partial_run",
    summary: "GitHub re-sync: 3 new repositories detected, React and TypeScript scores improved.",
    scoreChange: 8,
    skillsAffected: 3,
  },
  {
    id: "hist-3",
    date: "2026-03-10T09:00:00Z",
    type: "manual_update",
    summary: "LinkedIn connected. 24 endorsements imported across 6 skills.",
    scoreChange: 12,
    skillsAffected: 6,
  },
  {
    id: "hist-4",
    date: "2026-02-15T11:00:00Z",
    type: "full_run",
    summary: "Initial verification complete. 6 skills verified, 4 need additional evidence.",
    scoreChange: 48,
    skillsAffected: 10,
  },
  {
    id: "hist-5",
    date: "2026-01-20T15:00:00Z",
    type: "manual_update",
    summary: "AWS certification marked as expired. Score reduced for AWS skill.",
    scoreChange: -5,
    skillsAffected: 1,
  },
  {
    id: "hist-6",
    date: "2025-12-01T08:00:00Z",
    type: "full_run",
    summary: "First verification run. Resume parsed, 12 skills extracted.",
    scoreChange: 25,
    skillsAffected: 12,
  },
]
