spring.application.name=webgen-backend
spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-5
spring.ai.openai.chat.options.max-completion-tokens=15000
spring.ai.openai.chat.options.temperature=1
spring.ai.openai.chat.options.response-format.type=json_object


supabase.project.url = https://cadbniefkusbfkhmkptz.supabase.co