spring.config.activate.on-profile=dev

# CORS for local dev Next.js port
cors.allowed.origins=http://localhost:3000

# Supabase & OpenAi Connections
supabase.project.url = ${SUPABASE_PROJECT_URL}
spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY}

logging.level.org.springframework=INFO

